[0m11:24:10.537954 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D666951A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D664B11310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D667A87D90>]}


============================== 11:24:10.543623 | fdad4d7f-fb5b-4bd7-b473-e5a2630f9b58 ==============================
[0m11:24:10.543623 [info ] [MainThread]: Running with dbt=1.9.3
[0m11:24:10.544637 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\NHALIMAN\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init jaffle_shop', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:24:10.579124 [debug] [MainThread]: Starter project path: C:\Users\NHALIMAN\projects\nhaliman\Lib\site-packages\dbt\include\starter_project
[0m11:24:10.616548 [info ] [MainThread]: 
Your new dbt project "jaffle_shop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:24:10.619290 [info ] [MainThread]: Setting up your profile.
[0m11:32:58.619721 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C984FC5550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C983159310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C9860C7ED0>]}


============================== 11:32:58.625011 | be4e9b86-6c0d-42b0-9dcb-d73d1cd5eb57 ==============================
[0m11:32:58.625011 [info ] [MainThread]: Running with dbt=1.9.3
[0m11:32:58.625752 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\NHALIMAN\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m11:32:58.626218 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\NHALIMAN\projects\dbt_practice\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:32:58.627258 [debug] [MainThread]: Command `dbt run` failed at 11:32:58.627123 after 0.14 seconds
[0m11:32:58.627643 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C9860E10F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C985FBEB10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001C985F75F20>]}
[0m11:32:58.628062 [debug] [MainThread]: Flushing usage events
[0m11:32:59.592560 [debug] [MainThread]: An error was encountered while trying to flush usage events
